### ISSUE TITLE
Arrow functions for lexical this

### ISSUE THREAD

**Issue by domfarolino** [kentcdodds/es6-todomvc#25]
Just briefly looking at some of the code in this repository I see the pattern `var that = this;` in a lot of places. If I'm not mistaken this can be eliminated with the use of ES6 arrow functions as they support lexical this right? If so, I'd be willing to work on a PR if that is something that would be considered.

------

One such example: https://github.com/kentcdodds/es6-todomvc/blob/master/src/view.js#L63 that could be made more "ES6"-like

**Comment by kentcdodds** [comment]
Thanks for pointing it out, but the code itself is less important than configuring the tools which is why I didn't spend much time with migrating code to ES6. Under normal circumstances, I'd happily accept a pull request, but due to the difficulties propogating changes through the various branches, I'd prefer to only make changes when they're absolutely necessary.

**Comment by domfarolino** [comment]
No problem. Yeah I didn't see the plethora of branches in this repo haha, that would be tough.
