### ISSUE TITLE
Error on npm run validate

### ISSUE THREAD

**Issue by wlingke** [kentcdodds/es6-todomvc#8]
After I clone and run npm install, I tried to run "npm run validate" as suggested and received this error:
![capture](https://cloud.githubusercontent.com/assets/3145536/17265911/dcd97c06-55a7-11e6-846d-60b57dc017fc.PNG)

**Comment by kentcdodds** [comment]
This project requires you have Node 6 installed. I recommend you use nvm to install that and manage node versions.

**Comment by wlingke** [comment]
got it thanks

**Comment by wlingke** [comment]
Sorry - now I am getting a host of new errors after switching to Node 6.

![capture](https://cloud.githubusercontent.com/assets/3145536/17266092/65f1b732-55a9-11e6-9e41-5a29aaa78f8b.PNG)

**Comment by kentcdodds** [comment]
Yeah, that issue is because the way you have git setup to using `windows`-based line endings rather than `unix`-based line endings. I've updated the project to include a `.gitattributes` which will enforce the `unix`-based line endings so you should be able to [update your fork](http://stackoverflow.com/a/7244456/971592) and everything is working. If not, you could always delete your fork and re-fork it.

**Comment by wlingke** [comment]
Thanks!
